title:  Jekyll Site Example
description: Example site description. 
copyright_year_start: 2020
copyright_owner: Tim Brockley.
copyright_terms: All Rights Reserved.
url: "http://jekyll.timbrockley.co.uk"
